name: 'update_manifest'

# This will trigger the action on each push to the `release` branch.
on:
  push:
    branches:
      - feature/automatic-updates

jobs:
  publish-tauri:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Update Manifest
        run: node scripts/updateManifest.cjs
        env:
          APP_VERSION: 0.0.8
          # MACOS_ARTIFACT_PATHS: ${{ steps.Build_for_macos.outputs.artifactPaths }}
          # NON_MACOS_ARTIFACT_PATHS: ${{ steps.Build_for_non_macos.outputs.artifactPaths }}
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}

